import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { useMemo } from "react";
import styles from "./styles.module.css";

import { ListSlow, ListDeferred } from "./components/List";

export default function Home() {
  const [demo, setDemo] = useState("slow");
  const [input, setInput] = useState("");

  function handleChange(e) {
    setInput(e.target.value);
  }
  return (
    <div className="container">
      <Head>
        <title>UseDeferredValue Hook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>UseDeferredValue Hook</h1>
        <p>
          from https://blog.webdevsimplified.com/2022-05/use-deferred-value/
        </p>
      </header>

      <main>
        <fieldset className="f">
          {["fast", "slow"].map((item) => (
            <div key={item}>
              <input
                type="radio"
                id={item}
                name="demo"
                value={item}
                checked={item === demo}
                onClick={() => {
                  setDemo(item);
                }}
              />
              <label for={demo}>Slow</label>
            </div>
          ))}
        </fieldset>

        {demo === "slow" && (
          <div>
            <h2>List slow</h2>
            <input type="text" value={input} onChange={handleChange} />
            <ListSlow input={input} />
          </div>
        )}
        {demo === "fast" && (
          <div>
            <h2>List Deferred</h2>
            <input type="text" value={input} onChange={handleChange} />
            <ListDeferred input={input} />
          </div>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
